### ISSUE TITLE
MIgrate to `dotenvy`

### ISSUE THREAD

**Issue by itsyaasir** [collinsmuriuki/mpesa-rust#46] opened 2022-11-19 17:09 UTC
`dotenv` crate is no longer maintained, best alternative suggested is `dotenvy` which is fork of the original crate `dotenv`.
See this [issue](https://github.com/collinsmuriuki/mpesa-rust/issues/43)

**Comment by collinsmuriuki** [comment] 2023-02-10 06:35
@crispinkoech interested in working on this?

**Comment by crispinkoech** [comment] 2023-02-10 13:53
Sure 👍

**Comment by collinsmuriuki** [comment] 2023-02-15 14:47
@crispinkoech unassigning you since @itsyaasir is already working on this on #59

**Comment by collinsmuriuki** [comment] 2023-02-15 14:48
Also closed since this is a duplicate of #43

**Closed by collinsmuriuki** 2023-02-15 14:47 UTC
Labels: enhancement, good first issue

**Comment by crispinkoech** [comment] 2023-02-15 14:52
No worries 👍
